name: Build Windows Wheel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        platform: [windows-latest]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install locally
        run: |
          python -m pip install torch==2.6.0 torchaudio
          python -m pip install --upgrade pip==23.3.2
          python -m pip install wheel ninja

      - name: Install Deps
        run: python -m pip install .

      - name: Build the wheel
        run: python setup.py bdist_wheel -d dist/

      - run: du -h dist/*

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl